export const items = [
  {
    id: 1,
    category: "mobiles",
    title: "Apple iphone 14",
    imgSrc: "/Images/phone.png",
    price: 89999,
  },
  {
    id: 5,
    category: "laptop",
    title: "Samsung laptop 14",
    imgSrc: "/Images/laptop.png",
    price: 49999,
  },
  {
    id: 7,
    category: "tablet",
    title: "Apple tablet 14",
    imgSrc: "/Images/tablet.png",
    price: 29999,
  },
  {
    id: 2,
    category: "mobiles",
    title: "Apple iphone 14",
    imgSrc: "/Images/phone.png",
    price: 79999,
  },
  {
    id: 6,
    category: "tablet",
    title: "Samsung tablet 14",
    imgSrc: "/Images/tablet.png",
    price: 19999,
  },

  {
    id: 3,
    category: "mobiles",
    title: "Apple iphone 14",
    imgSrc: "/Images/phone.png",
    price: 69999,
  },
  {
    id: 4,
    category: "laptop",
    title: "Samsung iphone 14",
    imgSrc: "/Images/laptop.png",
    price: 69999,
  },
  {
    id: 9,
    category: "tablet",
    title: "Apple iphone 14",
    imgSrc: "/Images/tablet.png",
    price: 69999,
  },
  {
    id: 8,
    category: "laptop",
    title: "Samsung iphone 14",
    imgSrc: "/Images/laptop.png",
    price: 19999,
  },
];
